{% set name = "opentelemetry-api" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_api-{{ version }}.tar.gz
  sha256: 79ab791b4aaad27acc3dc3ba01596db5b5aac2ef75c70622c6038051d6c2cded

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
  run:
    - deprecated >=1.2.6
    - python >=3.7
    - setuptools >=16.0

test:
  imports:
    - opentelemetry
    - opentelemetry.context
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/master/opentelemetry-api
  summary: OpenTelemetry Python API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
    - marcelotrevisani
